language: cpp
services:
  - docker
sudo: required
compiler:
- gcc
before_install:
- docker pull matrim/cmake-examples:3.5.1
- docker pull matrim/cmake-examples:3.10.3
script:
- docker run --rm -v $PWD:/data/code -e DEV_UID=`id -u` -e DEV_GID=`id -g` -it matrim/cmake-examples:3.5.1 /data/code/test.sh
- docker run --rm -v $PWD:/data/code -e DEV_UID=`id -u` -e DEV_GID=`id -g` -it matrim/cmake-examples:3.10.3 /data/code/test.sh
branches:
  except:
  - gh-pages
notifications:
  email: true
os:
- linux
